### ISSUE TITLE
remove code duplication between render_key_title and render_key_title2

### ISSUE THREAD

**Issue by bjarthur** [GiovineItalia/Gadfly.jl#1385]
per https://github.com/GiovineItalia/Gadfly.jl/pull/1379#discussion_r368237119

**Comment by Mattriks** [comment]
Following #1386 here is a list of things to be done (in no order):

- [ ] take absolute point sizes into account in setting axis limits
- [ ] Syntax `Guide.colorkey(nothing)` to remove individual keys
- [ ] fix triggering of `Guide.shapekey` (#1366)
- [ ] Switch discrete `color` aesthetic to use `render_discrete_key` (will fix #859)
- [ ] key stacking (#766)
- [ ] tidy up render_key_title and render_key_title2

And in the distance:
- [ ] Allow 1 discrete color key and 1 continuous color key per plot (#1098, #1171)
